/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        hand:  ['Anthropic Serif Text', 'Georgia', 'serif'],
        print: ['Open Sans', 'sans-serif'],
        serif: ['Anthropic Serif Display', 'Georgia', 'serif'],
        sans:  ['Anthropic Sans Text', 'Open Sans', '-apple-system', 'sans-serif'],
      },
      colors: {
        cream:  {
          DEFAULT: '#faf9f5',
          paper: '#f0eee6',
          card: '#ffffff',
          100: '#faf9f5',
          200: '#f0eee6',
          300: '#e5e2d9',
          400: '#d6d3c7',
          500: '#c5c2b4',
        },
        coral:  { DEFAULT: '#2c2b25', dark: '#1f1e1a' },
        terra:  {
          DEFAULT: '#5e5b4e',
          light: '#7c7968',
          50: '#f5f4f0',
          100: '#eae9e4',
          200: '#d6d3c7',
          300: '#b5b2a4',
          400: '#7c7968',
          500: '#5e5b4e',
          600: '#4a483e',
          700: '#3a3831',
        },
        honey:  '#b4c6d4',
        sage:   '#b5c5c0',
        rose:   '#c5bfd9',
        ink:    {
          DEFAULT: '#2c2b25',
          soft: '#5e5b4e',
          800: '#4a4840',
          900: '#2c2b25',
        },
        charcoal: {
          800: '#4a4840',
          900: '#2c2b25',
        },
        line:   '#e5e2d9',
        // shadcn/ui vars
        border: "hsl(var(--border))",
        input:  "hsl(var(--input))",
        ring:   "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground:  "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive) / <alpha-value>)", foreground: "hsl(var(--destructive-foreground) / <alpha-value>)" },
        muted:   { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent:  { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card:    { DEFAULT: "hsl(var(--card))",    foreground: "hsl(var(--card-foreground))"    },
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs:        "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        warm:      "0 4px 24px rgba(0,0,0,.06)",
        'warm-lg': "0 8px 40px rgba(0,0,0,.08)",
        card:      "0 4px 16px rgba(0,0,0,.06)",
        polaroid:  "0 4px 16px rgba(0,0,0,.06)",
        btn:       "0 2px 8px rgba(0,0,0,.12)",
        'btn-hover': "0 4px 12px rgba(0,0,0,.16)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up":   { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "caret-blink":    { "0%,70%,100%": { opacity: "1" }, "20%,50%": { opacity: "0" } },
        shimmer:          { "100%": { transform: "translateX(100%)" } },
        "bounce-scroll":  { "0%,100%": { transform: "translateY(0)", opacity: "0.5" }, "50%": { transform: "translateY(10px)", opacity: "1" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up":   "accordion-up 0.2s ease-out",
        "caret-blink":    "caret-blink 1.25s ease-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
